lib/elefanto_web/router.ex
defmodule ElefantoWeb.Router do
  use ElefantoWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(ElefantoWeb.SetLocale)
    plug(ElefantoWeb.Plugs.FetchUser)
  end

  pipeline :api do
    plug(:accepts, ["json", "json-api"])
    # plug(JaSerializer.ContentTypeNegotiation)
    plug(JaSerializer.Deserializer)
  end

  scope "/api", ElefantoWeb do
    pipe_through(:api)

    resources("/posts", PostJsonController, except: [:new, :edit])
    resources("/comments", CommentController, only: [:create, :delete])
    get("/slugify_title", PostJsonController, :slugify)
  end

  scope "/", ElefantoWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    forward("/posts", Redirector)

    resources("/blog", PostController, except: [:create, :update], param: "slug")

    patch("/blog/:slug/publish", PostController, :publish, as: :post)
    patch("/blog/:slug/unpublish", PostController, :unpublish, as: :post)

    resources("/files", FileController, only: [:create, :show], param: "slug")
    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    get("/logout", SessionController, :delete)
  end

  defp handle_errors(conn, opts) do
    ElefantoWeb.RollbarReporter.handle_errors(conn, opts)
  end
end

lib/elefanto_web/views/shared_view.ex
defmodule ElefantoWeb.SharedView do
  use ElefantoWeb, :view
  import Phoenix.Controller, only: [current_url: 1, current_url: 2]

  def readable_model_name(%Ecto.Changeset{} = changeset) do
    changeset.data.__struct__
    |> Atom.to_string()
    |> String.split(".")
    |> List.last()
    |> String.downcase()
  end
end

lib/elefanto_web/templates/shared/_error_explanation.html.eex
<%= unless @changeset.valid? do %>
<div class="flash is-error">
<% count = Enum.count(@changeset.errors) %>
<h4><%= if (count > 1), do: [count, " errors"], else: "An error" %> prohibited this <%= readable_model_name(@changeset) %> from being saved:</h4>
<ul>
<%= for {key, {message, _}} <- @changeset.errors do %>
<li><%= key |> Atom.to_string |> String.capitalize %> <%= message %></li>
<% end %>
</ul>
</div>
<% end %>

lib/elefanto_web/templates/shared/_footer.html.eex
<footer class="footer">
  <div class="container has-text-centered">
<%= if @current_user do %>
<p>You are signed in as <%= @current_user.email %>. <%= link "Sign out", to: session_path(@conn, :delete) %></p>
<% end %>
<p>&copy; 2008-2018 <a href="mailto:k.j.moroz@gmail.com">Karol Moroz</a>. <%= gettext "Some rights reserved." %></p>
  </div>
</footer>

lib/elefanto_web/templates/shared/_ga.html.eex
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-124350889-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-124350889-1');
</script>

lib/elefanto_web/templates/shared/_header.html.eex
<header class="page-header">
  <div class="page-header-left">
    <%= link to: "/", class: "logo" do %>
      <img src="<%= static_path(@conn, "/images/logo.svg") %>" alt="2137.io">
    <% end %>
    <h2 class="subheader"><%= gettext "The blog of Karol Moroz" %></h2>
  </div>
  <div class="page-header-right">
    <%= link gettext("Home"), to: "/" %>
    <%= link gettext("Blog"), to: "/blog" %>
<%= case Gettext.get_locale(ElefantoWeb.Gettext) do %>
<%= "en" -> %><%= link "中文", to: current_url(@conn, %{lang: "zh"}), title: "English version" %>
<%= "zh" -> %><%= link "EN", to: current_url(@conn, %{lang: "en"}), title: "中文版" %>
<% end %>
  </div>
</header>

lib/elefanto_web/templates/shared/_preamble.html.eex
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="Karol Moroz">
<title><%= if assigns[:title], do: [assigns[:title], " | "] %>2137.io</title>
<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">